export let Eng = {
    dashboard: "Dashboard",
    income: "Income",
    expenses: "Expenses",
    donerparty: "Doner-Party",
    logout: "Logout",
    total: "Total",
    name: "Name",
    moblie: "Moblie_Number",
    amount: "Amount",
    description: "Detail",
    referencename: "Reference_Name",
    village: "Village",
    taluk: "Taluk",
    district: "District",
    donation_amount: "Donation_Amount",
    amounts: "Payment Method",
    modeofpatment1: "Full Payment",
    modeofpatment2: "Installments",
    construction: "Construction",
    landdonation: "Land Donation",
    anushthan: "Bijamantra-Anushthan",
    saintscokking: "Saints Cooking ",
    thakorjithal: "Thakorji Thal",
    otherdonations: "Other donations",
    view: "View",
    owner: "Manager_No",
    dontationdate: "Dontation_Date",
    cash: "Cash",
    bank: "Bank",
    salary: "Salary",
    rent: "Rent",
    lightbill: "Light-Bill",
    vegetables: "Vegetables",
    dairy: "Dairy",
    grocery: "Grocery",
    gasbill: "Gas bill",
    petroldiesel: "Petrol/Diesel",
    nameyup: "Name is required",
    detailyup: "Detail incomplete",
    modeofpaymentyup: "Select Payment Method",
    moblieyup: "Please enter a valid 10-digit mobile number",
    moblieyup2: "Phone number required"
}

export let Guj = {
    dashboard: "ડેશબોર્ડ",
    income: "આવક",
    expenses: "ખર્ચ",
    donerparty: "દાતા",
    logout: "લૉગ આઉટ",
    total: "કુલ",
    name: "નામ",
    moblie: "મોબાઈલ નંબર",
    amount: "રકમ",
    description: "વિગત",
    referencename: "હસ્તક નામ",
    village: "ગામ",
    taluk: "તાલુકો",
    district: "જીલ્લો",
    donation_amount: "દાન-રકમ",
    amounts: "ચુકવણી પદ્ધતિ",
    modeofpatment1: "સંપૂર્ણ દાન",
    modeofpatment2: " હપ્તે દાન",
    construction: "બાંધકામ",
    landdonation: "ભૂમિદાન",
    anushthan: "બીજમંત્ર-અનુષ્ઠાન",
    saintscokking: "સંતો રસોઈ",
    thakorjithal: "ઠાકોરજી થાળ",
    otherdonations: "અન્ય દાન",
    view: "જુઓ",
    owner: "મહેતાજી નંબર",
    dontationdate: "દાન તારીખ",
    cash: "કેશ",
    bank: "બઁક",
    salary: "પગાર",
    rent: "ભાડું",
    lightbill: "લાઇટ-બિલ",
    vegetables: "શાકભાજી",
    dairy: "ડેરી",
    grocery: "કરિયાણું",
    gasbill: "ગેસ બિલ",
    petroldiesel: "પેટ્રોલ /ડીઝલ",
    nameyup: "નામ જરૂરી છે",
    detailyup: "વિગત અધૂરી",
    modeofpaymentyup: "ચુકવણી પદ્ધતિ પસંદ કરો",
    moblieyup: "કૃપા કરીને માન્ય 10-અંકનો મોબાઇલ નંબર દાખલ કરો",
    moblieyup2: "ફોન નંબર જરૂરી છે"

}





